# Generated by Django 3.2.20 on 2023-11-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('office_staff', 'Office_Staff')], default='admin', max_length=15),
        ),
    ]
