# Generated by Django 3.2.20 on 2023-11-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionFor', models.CharField(choices=[('Class1', 'Class 1'), ('Class2', 'Class 2')], default='Class1', max_length=7)),
                ('admissionGroup', models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('General', 'General')], default='Science', max_length=9)),
                ('studentFirstName', models.CharField(max_length=100)),
                ('studentLastName', models.CharField(max_length=100)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentPhoneNumber', models.CharField(max_length=15)),
                ('studentImage', models.ImageField(upload_to='student_images/')),
                ('studentSignature', models.ImageField(upload_to='student_signatures/')),
                ('studentGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('studentReligion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism')], default='Islam', max_length=15)),
                ('studentNationality', models.CharField(choices=[('Bangladeshi', 'Bangladeshi')], default='Bangladesh', max_length=15)),
                ('birthDate', models.DateField()),
                ('birthCertificateNumber', models.PositiveIntegerField()),
                ('fatherName', models.CharField(max_length=100)),
                ('fatherNID', models.PositiveIntegerField()),
                ('fatherPhoneNumber', models.CharField(max_length=15)),
                ('fatherOccupation', models.CharField(max_length=100)),
                ('fatherReligion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism')], default='Islam', max_length=15)),
                ('fatherMonthlyIncome', models.PositiveIntegerField()),
                ('fatherNationality', models.CharField(choices=[('Bangladeshi', 'Bangladeshi')], default='Bangladesh', max_length=15)),
                ('motherName', models.CharField(max_length=100)),
                ('motherNID', models.PositiveIntegerField()),
                ('motherPhoneNumber', models.CharField(max_length=15)),
                ('motherOccupation', models.CharField(max_length=100)),
                ('motherReligion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism')], default='Islam', max_length=15)),
                ('motherMonthlyIncome', models.PositiveIntegerField()),
                ('motherNationality', models.CharField(choices=[('Bangladeshi', 'Bangladeshi')], default='Bangladesh', max_length=15)),
                ('presentAddressLine1', models.CharField(max_length=100)),
                ('presentAddressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('presentZila', models.CharField(max_length=100)),
                ('presentThana', models.CharField(blank=True, max_length=100, null=True)),
                ('presentPostalCode', models.PositiveIntegerField()),
                ('permanentAddressLine1', models.CharField(max_length=100)),
                ('permanentAddressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('permanentZila', models.CharField(max_length=100)),
                ('permanentThana', models.CharField(blank=True, max_length=100, null=True)),
                ('permanentPostalCode', models.PositiveIntegerField()),
                ('previousClass', models.CharField(blank=True, max_length=100, null=True)),
                ('previousClassGroup', models.CharField(blank=True, choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('General', 'General')], default='Science', max_length=15, null=True)),
                ('previousClassResultTotalMark', models.PositiveIntegerField(blank=True, null=True)),
                ('previousClassResultGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('previousSchoolName', models.CharField(blank=True, max_length=100, null=True)),
                ('previousSchoolClassRoll', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
