# Generated by Django 3.2.20 on 2023-11-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classday', models.CharField(max_length=100)),
                ('teacherName', models.CharField(max_length=100)),
                ('subjectdata', models.TextField()),
            ],
        ),
    ]
