# Generated by Django 3.2.20 on 2023-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_classroutinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.CharField(default='undefined', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=500, upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='classroutinemodel',
            old_name='classday',
            new_name='classDay',
        ),
        migrations.RenameField(
            model_name='classroutinemodel',
            old_name='subjectdata',
            new_name='subjectData',
        ),
        migrations.AlterField(
            model_name='classroutinemodel',
            name='teacherName',
            field=models.TextField(max_length=100),
        ),
    ]
