# Generated by Django 3.2.20 on 2023-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20231111_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(default='student', max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
